#!/usr/bin/env python3
"""Joukowski cusp pullback demo for Q integration.

The point of this demo is narrow and auditable: for a classical airfoil cusp,
Q already has the natural cusp chart when the boundary is generated by the
Joukowski map.  The integration weights and chord kernel are generated from

    z(theta) = J(zeta(theta)),    J(zeta) = zeta + a^2 / zeta,

and the cusp is repaid by the vanishing Jacobian ``J'(zeta_c)=0`` rather than by
storing a dense matrix or applying an unrelated post-process.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from dataclasses import dataclass
from pathlib import Path
from time import perf_counter

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import torch


ROOT = Path(__file__).resolve().parents[2]
TAU = 2.0 * math.pi


@dataclass(frozen=True)
class JoukowskiParams:
    a: float = 1.0
    center_x: float = -0.10
    center_y: float = 0.08

    @property
    def radius(self) -> float:
        return math.hypot(self.a - self.center_x, -self.center_y)

    @property
    def cusp_theta(self) -> float:
        return math.atan2(-self.center_y, self.a - self.center_x)


@dataclass(frozen=True)
class BoundarySamples:
    phi: torch.Tensor
    points: torch.Tensor
    weights: torch.Tensor
    speed: torch.Tensor
    zeta_points: torch.Tensor
    cusp: torch.Tensor
    chord: float
    rule: str


def complex_from_xy(x: torch.Tensor | float, y: torch.Tensor | float) -> torch.Tensor:
    return torch.complex(torch.as_tensor(x, dtype=torch.float64), torch.as_tensor(y, dtype=torch.float64))


def normalization_constants(params: JoukowskiParams, *, sample_count: int = 32768) -> tuple[torch.Tensor, float]:
    dtype = torch.float64
    phi = torch.arange(sample_count, dtype=dtype) * (TAU / sample_count)
    theta = phi + params.cusp_theta
    radius = torch.tensor(params.radius, dtype=dtype)
    center = complex_from_xy(params.center_x, params.center_y)
    a = torch.tensor(params.a, dtype=dtype)
    zeta = center + radius * torch.complex(torch.cos(theta), torch.sin(theta))
    z = zeta + (a * a) / zeta
    min_x = torch.min(z.real)
    max_x = torch.max(z.real)
    return min_x, float(max_x - min_x)


def joukowski_boundary(sample_count: int, params: JoukowskiParams, *, phase: float = 0.5) -> BoundarySamples:
    dtype = torch.float64
    phi = (torch.arange(sample_count, dtype=dtype) + phase) * (TAU / sample_count)
    theta = phi + params.cusp_theta
    radius = torch.tensor(params.radius, dtype=dtype)
    center = complex_from_xy(params.center_x, params.center_y)
    exp_theta = torch.complex(torch.cos(theta), torch.sin(theta))
    zeta = center + radius * exp_theta
    a = torch.tensor(params.a, dtype=dtype)
    z_complex = zeta + (a * a) / zeta

    cusp_complex = complex_from_xy(2.0 * params.a, 0.0)
    min_x, chord = normalization_constants(params)

    points = torch.stack(((z_complex.real - min_x) / chord, z_complex.imag / chord), dim=1)
    cusp = torch.stack(((cusp_complex.real - min_x) / chord, cusp_complex.imag / chord))

    dzeta = radius * torch.complex(-torch.sin(theta), torch.cos(theta))
    derivative = (1.0 - (a * a) / (zeta * zeta)) * dzeta
    speed = torch.abs(derivative) / chord
    weights = speed * (TAU / sample_count)
    return BoundarySamples(
        phi=phi,
        points=points,
        weights=weights,
        speed=speed,
        zeta_points=zeta,
        cusp=cusp,
        chord=chord,
        rule="joukowski_pullback",
    )


def cusp_density(phi: torch.Tensor) -> torch.Tensor:
    signed = torch.remainder(phi + math.pi, TAU) - math.pi
    cusp_bump = torch.exp(-0.5 * (signed / 0.075).square())
    return 1.0 + 0.22 * torch.cos(3.0 * phi) - 0.13 * torch.sin(5.0 * phi) + 0.85 * cusp_bump


def trace_values(phi: torch.Tensor) -> torch.Tensor:
    signed = torch.remainder(phi + math.pi, TAU) - math.pi
    cusp_bump = torch.exp(-0.5 * (signed / 0.10).square())
    return torch.cos(2.0 * phi) + 0.35 * torch.sin(5.0 * phi) + 0.55 * cusp_bump


def log_layer_integral(samples: BoundarySamples, target: torch.Tensor) -> float:
    density = cusp_density(samples.phi)
    delta = samples.points - target.unsqueeze(0)
    distance = torch.linalg.norm(delta, dim=1).clamp_min(1.0e-300)
    return float(torch.sum(samples.weights * density * torch.log(distance)))


def polygonal_arclength_resample(sample_count: int, params: JoukowskiParams, *, source_count: int = 262144) -> BoundarySamples:
    source = joukowski_boundary(source_count, params, phase=0.0)
    next_points = torch.roll(source.points, shifts=-1, dims=0)
    segment_lengths = torch.linalg.norm(next_points - source.points, dim=1)
    cumulative = torch.cat((torch.zeros(1, dtype=torch.float64), torch.cumsum(segment_lengths, dim=0)))
    total = cumulative[-1]
    targets = (torch.arange(sample_count, dtype=torch.float64) + 0.5) * (total / sample_count)
    segment_indices = torch.searchsorted(cumulative[1:], targets)
    local = (targets - cumulative[segment_indices]) / segment_lengths[segment_indices].clamp_min(1.0e-300)
    points = source.points[segment_indices] + local.unsqueeze(1) * (
        next_points[segment_indices] - source.points[segment_indices]
    )

    phi0 = source.phi[segment_indices]
    phi1 = phi0 + (TAU / source_count)
    phi = torch.remainder(phi0 + local * (phi1 - phi0), TAU)
    weights = torch.full((sample_count,), float(total / sample_count), dtype=torch.float64)
    speed = torch.full((sample_count,), float(total / TAU), dtype=torch.float64)
    return BoundarySamples(
        phi=phi,
        points=points,
        weights=weights,
        speed=speed,
        zeta_points=source.zeta_points[segment_indices],
        cusp=source.cusp,
        chord=source.chord,
        rule="equal_arclength",
    )


def q_energy_blockwise(samples: BoundarySamples, values: torch.Tensor, *, chunk_size: int) -> float:
    points = samples.points
    weights = samples.weights
    total = torch.tensor(0.0, dtype=torch.float64)
    n = points.shape[0]
    for start in range(0, n, chunk_size):
        stop = min(start + chunk_size, n)
        delta = points[start:stop, None, :] - points[None, :, :]
        distance2 = torch.sum(delta * delta, dim=2)
        for row, index in enumerate(range(start, stop)):
            distance2[row, index] = float("inf")
        value_delta = values[start:stop, None] - values[None, :]
        pair_weights = weights[start:stop, None] * weights[None, :]
        total = total + torch.sum(pair_weights * value_delta.square() / distance2)
    return float(0.5 * total / math.pi)


def local_scaling(params: JoukowskiParams) -> dict[str, list[float]]:
    powers = torch.arange(-7, -1, dtype=torch.float64)
    phi_abs = torch.pow(torch.tensor(10.0, dtype=torch.float64), powers)
    plus = joukowski_from_phi(phi_abs, params)
    minus = joukowski_from_phi(-phi_abs, params)
    cusp = joukowski_boundary(8, params).cusp
    distance = 0.5 * (
        torch.linalg.norm(plus - cusp.unsqueeze(0), dim=1) + torch.linalg.norm(minus - cusp.unsqueeze(0), dim=1)
    )
    speed_plus = speed_from_phi(phi_abs, params)
    speed_minus = speed_from_phi(-phi_abs, params)
    speed = 0.5 * (speed_plus + speed_minus)
    slope_distance = float(
        torch.linalg.lstsq(
            torch.stack((torch.log(phi_abs), torch.ones_like(phi_abs)), dim=1),
            torch.log(distance),
        ).solution[0]
    )
    slope_speed = float(
        torch.linalg.lstsq(
            torch.stack((torch.log(phi_abs), torch.ones_like(phi_abs)), dim=1),
            torch.log(speed),
        ).solution[0]
    )
    return {
        "phi_abs": [float(value) for value in phi_abs.tolist()],
        "distance_to_cusp": [float(value) for value in distance.tolist()],
        "speed": [float(value) for value in speed.tolist()],
        "distance_slope": slope_distance,
        "speed_slope": slope_speed,
    }


def joukowski_from_phi(phi: torch.Tensor, params: JoukowskiParams) -> torch.Tensor:
    theta = phi + params.cusp_theta
    radius = torch.tensor(params.radius, dtype=torch.float64)
    center = complex_from_xy(params.center_x, params.center_y)
    exp_theta = torch.complex(torch.cos(theta), torch.sin(theta))
    zeta = center + radius * exp_theta
    a = torch.tensor(params.a, dtype=torch.float64)
    z = zeta + (a * a) / zeta
    min_x, chord = normalization_constants(params)
    return torch.stack(((z.real - min_x) / chord, z.imag / chord), dim=1)


def speed_from_phi(phi: torch.Tensor, params: JoukowskiParams) -> torch.Tensor:
    theta = phi + params.cusp_theta
    radius = torch.tensor(params.radius, dtype=torch.float64)
    center = complex_from_xy(params.center_x, params.center_y)
    exp_theta = torch.complex(torch.cos(theta), torch.sin(theta))
    zeta = center + radius * exp_theta
    a = torch.tensor(params.a, dtype=torch.float64)
    dzeta = radius * torch.complex(-torch.sin(theta), torch.cos(theta))
    derivative = (1.0 - (a * a) / (zeta * zeta)) * dzeta
    _, chord = normalization_constants(params)
    return torch.abs(derivative) / chord


def regularization_diagnostics(params: JoukowskiParams, *, sample_count: int = 4096) -> dict[str, object]:
    samples = joukowski_boundary(sample_count, params, phase=0.5)
    cumulative_centers = torch.cumsum(samples.weights, dim=0) - 0.5 * samples.weights
    length = torch.sum(samples.weights)
    theta_fraction = samples.phi / TAU
    arclength_fraction = cumulative_centers / length
    deviation = arclength_fraction - theta_fraction
    equal_arc = polygonal_arclength_resample(512, params, source_count=65536)
    sorted_phi = torch.sort(equal_arc.phi).values
    gaps = torch.diff(torch.cat((sorted_phi, sorted_phi[:1] + TAU)))
    return {
        "theta_fraction": [float(value) for value in theta_fraction[::32].tolist()],
        "arclength_fraction": [float(value) for value in arclength_fraction[::32].tolist()],
        "speed": [float(value) for value in samples.speed[::32].tolist()],
        "max_abs_s_over_l_minus_theta_over_2pi": float(torch.max(torch.abs(deviation))),
        "speed_min": float(torch.min(samples.speed)),
        "speed_max": float(torch.max(samples.speed)),
        "speed_ratio_max_over_min_sampled": float(torch.max(samples.speed) / torch.min(samples.speed).clamp_min(1.0e-300)),
        "equal_arclength_circle_gap_min": float(torch.min(gaps)),
        "equal_arclength_circle_gap_max": float(torch.max(gaps)),
        "equal_arclength_circle_gap_ratio": float(torch.max(gaps) / torch.min(gaps).clamp_min(1.0e-300)),
    }


def ellipse_pullback_diagnostics(*, major: float = 3.0, minor: float = math.sqrt(5.0), sample_count: int = 4096) -> dict[str, object]:
    theta = (torch.arange(sample_count, dtype=torch.float64) + 0.5) * (TAU / sample_count)
    speed = torch.sqrt((major * torch.sin(theta)).square() + (minor * torch.cos(theta)).square())
    weights = speed * (TAU / sample_count)
    cumulative_centers = torch.cumsum(weights, dim=0) - 0.5 * weights
    length = torch.sum(weights)
    theta_fraction = theta / TAU
    arclength_fraction = cumulative_centers / length
    alpha = 0.5 * (major + minor)
    beta = 0.5 * (major - minor)
    return {
        "major": major,
        "minor": minor,
        "exterior_map_alpha": alpha,
        "exterior_map_beta": beta,
        "boundary_trace": "z(exp(i theta)) = major cos(theta) + i minor sin(theta)",
        "speed_formula": "ds/dtheta = sqrt(major^2 sin(theta)^2 + minor^2 cos(theta)^2)",
        "speed_min": float(torch.min(speed)),
        "speed_max": float(torch.max(speed)),
        "speed_ratio_max_over_min": float(torch.max(speed) / torch.min(speed)),
        "max_abs_s_over_l_minus_theta_over_2pi": float(torch.max(torch.abs(arclength_fraction - theta_fraction))),
    }


def run_demo(
    *,
    output_dir: Path,
    n_values: tuple[int, ...],
    reference_n: int,
    q_reference_n: int,
    chunk_size: int,
) -> dict[str, object]:
    output_dir.mkdir(parents=True, exist_ok=True)
    params = JoukowskiParams()

    reference = joukowski_boundary(reference_n, params, phase=0.5)
    target = reference.cusp + torch.tensor([-0.030, 0.065], dtype=torch.float64)
    reference_integral = log_layer_integral(reference, target)

    q_reference = joukowski_boundary(q_reference_n, params, phase=0.5)
    q_reference_energy = q_energy_blockwise(q_reference, trace_values(q_reference.phi), chunk_size=chunk_size)

    rows: list[dict[str, object]] = []
    for sample_count in n_values:
        start = perf_counter()
        pullback = joukowski_boundary(sample_count, params, phase=0.5)
        pullback_integral = log_layer_integral(pullback, target)
        pullback_energy = q_energy_blockwise(pullback, trace_values(pullback.phi), chunk_size=chunk_size)
        pullback_ms = 1000.0 * (perf_counter() - start)

        start = perf_counter()
        arclength = polygonal_arclength_resample(sample_count, params)
        arclength_integral = log_layer_integral(arclength, target)
        arclength_energy = q_energy_blockwise(arclength, trace_values(arclength.phi), chunk_size=chunk_size)
        arclength_ms = 1000.0 * (perf_counter() - start)

        rows.append(
            {
                "n": sample_count,
                "joukowski_integral": pullback_integral,
                "arclength_integral": arclength_integral,
                "reference_integral": reference_integral,
                "joukowski_integral_abs_error": abs(pullback_integral - reference_integral),
                "arclength_integral_abs_error": abs(arclength_integral - reference_integral),
                "joukowski_q_energy": pullback_energy,
                "arclength_q_energy": arclength_energy,
                "reference_q_energy": q_reference_energy,
                "joukowski_q_energy_rel_error": abs(pullback_energy - q_reference_energy)
                / max(abs(q_reference_energy), 1.0e-300),
                "arclength_q_energy_rel_error": abs(arclength_energy - q_reference_energy)
                / max(abs(q_reference_energy), 1.0e-300),
                "joukowski_ms": pullback_ms,
                "arclength_ms": arclength_ms,
            }
        )

    scaling = local_scaling(params)
    payload = {
        "method": {
            "dense_matrix_stored": False,
            "boundary_generator": "z(theta)=J(c+R exp(i(theta_c+theta))), J(zeta)=zeta+a^2/zeta",
            "borrow": "circle coordinate theta and Joukowski QJet generator",
            "compute": "physical chord distances and pullback weights |J'(zeta) zeta_theta| dtheta",
            "repay": "trailing-edge cusp is repaid by J'(zeta_c)=0, giving ds~|theta-theta_c|dtheta",
            "figure_3_check": "arclength-uniform samples do not generally map to equispaced circle samples; equispaced circle samples require metric weights or harmonic-measure resampling",
            "reference_n": reference_n,
            "q_reference_n": q_reference_n,
            "q_energy": "(1/(2*pi)) sum_ij w_i w_j (u_i-u_j)^2/|z_i-z_j|^2, evaluated blockwise",
        },
        "params": {
            "a": params.a,
            "center": [params.center_x, params.center_y],
            "radius": params.radius,
            "cusp_theta": params.cusp_theta,
            "normalized_cusp": [float(value) for value in reference.cusp.tolist()],
            "target": [float(value) for value in target.tolist()],
        },
        "local_scaling": scaling,
        "regularization": regularization_diagnostics(params),
        "ellipse_closed_form": ellipse_pullback_diagnostics(),
        "rows": rows,
    }

    csv_path = output_dir / "joukowski_q_cusp_integration.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        fieldnames = [
            "n",
            "joukowski_integral_abs_error",
            "arclength_integral_abs_error",
            "joukowski_q_energy_rel_error",
            "arclength_q_energy_rel_error",
            "joukowski_ms",
            "arclength_ms",
        ]
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row[key] for key in fieldnames})

    json_path = output_dir / "joukowski_q_cusp_integration.json"
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    figure_path = output_dir / "joukowski_q_cusp_integration.png"
    render_figure(params, payload, figure_path)

    report_path = output_dir / "joukowski_q_cusp_integration.md"
    write_report(payload, report_path, figure_path, csv_path, json_path)
    return {
        "csv": str(csv_path),
        "json": str(json_path),
        "figure": str(figure_path),
        "report": str(report_path),
        "rows": rows,
    }


def render_figure(params: JoukowskiParams, payload: dict[str, object], path: Path) -> None:
    plt.rcParams.update(
        {
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "axes.edgecolor": "0.15",
            "axes.labelcolor": "0.1",
            "xtick.color": "0.1",
            "ytick.color": "0.1",
            "text.color": "0.1",
            "font.size": 8,
            "axes.titlesize": 9,
            "axes.labelsize": 8,
            "legend.fontsize": 7,
            "lines.linewidth": 1.3,
        }
    )
    boundary = joukowski_boundary(900, params, phase=0.5)
    circle_theta = torch.arange(900, dtype=torch.float64) * (TAU / 900)
    center_x = params.center_x
    center_y = params.center_y
    circle_x = center_x + params.radius * torch.cos(circle_theta + params.cusp_theta)
    circle_y = center_y + params.radius * torch.sin(circle_theta + params.cusp_theta)

    rows = payload["rows"]
    scaling = payload["local_scaling"]
    regularization = payload["regularization"]
    assert isinstance(rows, list)
    assert isinstance(scaling, dict)
    assert isinstance(regularization, dict)
    ns = [int(row["n"]) for row in rows]
    j_int = [float(row["joukowski_integral_abs_error"]) for row in rows]
    a_int = [float(row["arclength_integral_abs_error"]) for row in rows]
    j_q = [float(row["joukowski_q_energy_rel_error"]) for row in rows]
    a_q = [float(row["arclength_q_energy_rel_error"]) for row in rows]

    fig, axes = plt.subplots(2, 3, figsize=(11.8, 6.9), constrained_layout=True)
    ax = axes[0, 0]
    ax.plot(circle_x.tolist(), circle_y.tolist(), color="0.45", label="circle preimage")
    ax.scatter([params.a], [0.0], color="0.05", s=22, label="critical point")
    ax.set_aspect("equal", adjustable="box")
    ax.set_title("Borrowed circle chart")
    ax.grid(True, color="0.88", linewidth=0.6)
    ax.legend(frameon=False)

    ax = axes[0, 1]
    ax.plot(boundary.points[:, 0].tolist(), boundary.points[:, 1].tolist(), color="0.05")
    ax.scatter([float(boundary.cusp[0])], [float(boundary.cusp[1])], color="0.05", s=22, label="J'(zeta)=0 cusp")
    target = torch.tensor(payload["params"]["target"], dtype=torch.float64)
    ax.scatter([float(target[0])], [float(target[1])], marker="x", color="0.35", s=28, label="near-cusp target")
    ax.set_aspect("equal", adjustable="box")
    ax.set_title("Physical Joukowski cusp")
    ax.grid(True, color="0.88", linewidth=0.6)
    ax.legend(frameon=False)

    ax = axes[0, 2]
    theta_fraction = regularization["theta_fraction"]
    arclength_fraction = regularization["arclength_fraction"]
    speed_samples = regularization["speed"]
    ax.plot(theta_fraction, arclength_fraction, color="0.05", label="s(theta)/L")
    ax.plot([0.0, 1.0], [0.0, 1.0], color="0.65", linestyle="--", label="identity")
    ax.set_title("Metric regularization")
    ax.set_xlabel("theta / 2pi")
    ax.set_ylabel("arclength fraction")
    ax.grid(True, color="0.88", linewidth=0.6)
    ax.legend(frameon=False, loc="upper left")
    ax2 = ax.twinx()
    ax2.plot(theta_fraction, speed_samples, color="0.45", linewidth=0.9, alpha=0.7, label="ds/dtheta")
    ax2.set_ylabel("ds/dtheta")
    ax2.tick_params(axis="y", colors="0.35")

    ax = axes[1, 0]
    ax.loglog(scaling["phi_abs"], scaling["distance_to_cusp"], marker="o", color="0.05", label=f"|z-zc| slope {scaling['distance_slope']:.2f}")
    ax.loglog(scaling["phi_abs"], scaling["speed"], marker="s", color="0.55", label=f"ds/dtheta slope {scaling['speed_slope']:.2f}")
    ax.set_title("Local cusp scaling")
    ax.set_xlabel("|theta-theta_c|")
    ax.set_ylabel("normalized magnitude")
    ax.grid(True, which="both", color="0.88", linewidth=0.6)
    ax.legend(frameon=False)

    ax = axes[1, 1]
    ax.loglog(ns, j_int, marker="o", color="0.05", label="Joukowski log integral")
    ax.loglog(ns, a_int, marker="o", linestyle="--", color="0.55", label="equal arclength log integral")
    ax.loglog(ns, j_q, marker="s", color="0.20", label="Joukowski Q energy")
    ax.loglog(ns, a_q, marker="s", linestyle="--", color="0.72", label="equal arclength Q energy")
    ax.set_title("Cusp-aware convergence")
    ax.set_xlabel("boundary nodes n")
    ax.set_ylabel("error vs fine reference")
    ax.grid(True, which="both", color="0.88", linewidth=0.6)
    ax.legend(frameon=False)

    ax = axes[1, 2]
    latest = rows[-1]
    labels = ["log integral", "Q energy"]
    joukowski_values = [
        float(latest["joukowski_integral_abs_error"]),
        float(latest["joukowski_q_energy_rel_error"]),
    ]
    arclength_values = [
        float(latest["arclength_integral_abs_error"]),
        float(latest["arclength_q_energy_rel_error"]),
    ]
    positions = [0.0, 1.0]
    width = 0.34
    ax.bar([position - width / 2.0 for position in positions], joukowski_values, width=width, color="0.15", label="Joukowski")
    ax.bar([position + width / 2.0 for position in positions], arclength_values, width=width, color="0.65", label="equal arclength")
    ax.set_yscale("log")
    ax.set_xticks(positions)
    ax.set_xticklabels(labels)
    ax.set_title(f"Latest n={latest['n']}")
    ax.set_ylabel("error")
    ax.grid(True, which="both", axis="y", color="0.88", linewidth=0.6)
    ax.legend(frameon=False)

    fig.suptitle("Q Integration Through the Joukowski Cusp Pullback", fontsize=10)
    fig.savefig(path, dpi=220)
    plt.close(fig)


def compact(value: object) -> str:
    return f"{float(value):.3e}"


def write_report(payload: dict[str, object], report_path: Path, figure_path: Path, csv_path: Path, json_path: Path) -> None:
    method = payload["method"]
    params = payload["params"]
    scaling = payload["local_scaling"]
    regularization = payload["regularization"]
    ellipse = payload["ellipse_closed_form"]
    rows = payload["rows"]
    assert isinstance(method, dict)
    assert isinstance(params, dict)
    assert isinstance(scaling, dict)
    assert isinstance(regularization, dict)
    assert isinstance(ellipse, dict)
    assert isinstance(rows, list)
    latest = rows[-1]

    lines = [
        "# Joukowski Q Cusp Integration",
        "",
        "This demo shows the cusp case where Q naturally uses a Joukowski pullback rather than an external dense correction.",
        "",
        f"![Joukowski Q cusp integration]({figure_path})",
        "",
        "## Figure 3 Check",
        "",
        "I checked the current Cauchy transport PDF, page 11. Figure 3 says the exterior Riemann map carries arclength samples to equispaced circle samples. Read literally, that is not true for a generic analytic boundary.",
        "",
        "The correct statement is:",
        "",
        "```text",
        "theta = arg Phi(z)",
        "dtheta = |Phi'(gamma(s))| ds",
        "ds = |(Phi^{-1})'(e^{i theta}) i e^{i theta}| dtheta",
        "```",
        "",
        "So arclength-uniform samples map to equispaced circle angles only if `|Phi'(gamma(s))|` is constant along the boundary. In general, equispaced circle samples are harmonic-measure samples on Γ, not arclength-uniform samples. The regularization is the metric weight `ds/dtheta`.",
        "",
        "In this Joukowski cusp run, the measured nonuniformity is explicit:",
        "",
        f"- `max |s(theta)/L - theta/(2pi)| = {float(regularization['max_abs_s_over_l_minus_theta_over_2pi']):.3e}`",
        f"- sampled `max(ds/dtheta) / min(ds/dtheta) = {float(regularization['speed_ratio_max_over_min_sampled']):.3e}`",
        f"- if 512 arclength-uniform samples are mapped back to circle angles, the largest angle gap is `{float(regularization['equal_arclength_circle_gap_ratio']):.3e}x` the smallest",
        "",
        "## Closed-Form Ellipse Sanity Check",
        "",
        "For the ellipse in your note, with semi-axes `a=3` and `b=sqrt(5)`, the exterior map is the Joukowski-type Laurent map",
        "",
        "```text",
        "z(w) = alpha w + beta w^(-1)",
        "alpha = (3 + sqrt(5))/2",
        "beta  = (3 - sqrt(5))/2",
        "```",
        "",
        "On `|w|=1`, `w=exp(i theta)`, this gives exactly",
        "",
        "```text",
        "z(exp(i theta)) = 3 cos(theta) + i sqrt(5) sin(theta).",
        "```",
        "",
        "So the conic/ellipse pullback is closed-form. No Schwarz-Christoffel or Beltrami solve is needed. But it is still not arclength-preserving unless `a=b`:",
        "",
        "```text",
        "ds/dtheta = sqrt(9 sin(theta)^2 + 5 cos(theta)^2).",
        "```",
        "",
        f"For this ellipse, `max(ds/dtheta)/min(ds/dtheta) = {float(ellipse['speed_ratio_max_over_min']):.6f}` and `max |s(theta)/L - theta/(2pi)| = {float(ellipse['max_abs_s_over_l_minus_theta_over_2pi']):.3e}`. This is the benign smooth version of the same regularization: equispaced circle samples are valid when carried with the metric weight.",
        "",
        "## Intrinsic Pullback",
        "",
        "The generator is",
        "",
        "```text",
        "zeta(theta) = c + R exp(i(theta_c + theta))",
        "J(zeta) = zeta + a^2 / zeta",
        "z(theta) = J(zeta(theta))",
        "```",
        "",
        "The circle is chosen so it passes through the critical point `zeta_c = a`. Therefore `J'(zeta_c)=0` and the trailing edge is a cusp.",
        "",
        "The Q ingredients are generated, not stored:",
        "",
        "```text",
        "w_i = |J'(zeta_i) zeta_theta_i| Delta theta",
        "Q[u]_i = (1/pi) sum_j w_j (u_i - u_j) / |J(zeta_i)-J(zeta_j)|^2",
        "I[target] = sum_i w_i sigma_i log |target - J(zeta_i)|",
        "```",
        "",
        "This is the regularized version of the Figure 3 diagram: choose equispaced `theta_j` on the circle, evaluate physical points through the inverse chart, and carry the metric weights. If instead one starts from arclength samples on Γ, the corresponding `theta_j` are nonuniform and need resampling, NUFFT, FMM, or an H-matrix path.",
        "",
        "Near the cusp, the local expansion is quadratic:",
        "",
        "```text",
        "z - z_c = 0.5 J''(zeta_c) (zeta-zeta_c)^2 + ...",
        "ds/dtheta ~ C |theta-theta_c|",
        "```",
        "",
        f"Measured local slopes: `|z-z_c| ~ |theta|^{float(scaling['distance_slope']):.3f}` and `ds/dtheta ~ |theta|^{float(scaling['speed_slope']):.3f}`.",
        "",
        "## Latest Numerical Result",
        "",
        "| n | Joukowski log abs err | Equal-arclength log abs err | Joukowski Q energy rel err | Equal-arclength Q energy rel err |",
        "|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        lines.append(
            "| {n} | `{jlog}` | `{alog}` | `{jq}` | `{aq}` |".format(
                n=row["n"],
                jlog=compact(row["joukowski_integral_abs_error"]),
                alog=compact(row["arclength_integral_abs_error"]),
                jq=compact(row["joukowski_q_energy_rel_error"]),
                aq=compact(row["arclength_q_energy_rel_error"]),
            )
        )

    lines.extend(
        [
            "",
            "At the finest tested level, the intrinsic Joukowski pullback gives:",
            "",
            f"- log-layer error `{compact(latest['joukowski_integral_abs_error'])}` vs equal-arclength `{compact(latest['arclength_integral_abs_error'])}`",
            f"- Q-energy relative error `{compact(latest['joukowski_q_energy_rel_error'])}` vs equal-arclength `{compact(latest['arclength_q_energy_rel_error'])}`",
            "",
            "## Interpretation",
            "",
            "For cusps, the natural Q protocol is exactly the Joukowski-style pullback: borrow the nonsingular circle coordinate, compute physical chord distances and pullback weights, then repay the cusp through the vanishing Jacobian. This is different from polygon corners, where the relevant local model is a wedge with Kondrat'ev/Mellin exponents.",
            "",
            "The equal-arclength baseline is not wrong; it is just blind to the square-root inverse chart. The Joukowski generator puts resolution where the cusp chart says the physical boundary compresses.",
            "",
            "## Run Parameters",
            "",
            f"- dense matrix stored: `{method['dense_matrix_stored']}`",
            f"- reference log integral nodes: `{method['reference_n']}`",
            f"- reference Q energy nodes: `{method['q_reference_n']}`",
            f"- normalized cusp: `{params['normalized_cusp']}`",
            f"- near-cusp target: `{params['target']}`",
            "",
            "## Artifacts",
            "",
            f"- CSV: `{csv_path}`",
            f"- JSON: `{json_path}`",
            f"- Figure: `{figure_path}`",
        ]
    )
    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=ROOT / "outputs" / "joukowski_q_cusp_integration")
    parser.add_argument("--n-values", type=int, nargs="+", default=(128, 256, 512, 1024, 2048))
    parser.add_argument("--reference-n", type=int, default=262144)
    parser.add_argument("--q-reference-n", type=int, default=4096)
    parser.add_argument("--chunk-size", type=int, default=192)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    result = run_demo(
        output_dir=args.output_dir,
        n_values=tuple(args.n_values),
        reference_n=args.reference_n,
        q_reference_n=args.q_reference_n,
        chunk_size=args.chunk_size,
    )
    print(json.dumps({key: value for key, value in result.items() if key != "rows"}, indent=2))


if __name__ == "__main__":
    main()
