"""Public API for the production Gulati Q quadrature pipeline.

The facade keeps the paper-facing path narrow:

* ordered boundary samples generate QJets;
* DtN/PDE solves use harmonic moment and zeta-tail repayment by default;
* near-boundary log-layer quadrature uses multipole/zeta Q;
* arithmetic certificates are exposed without forming dense Q matrices.

The older :mod:`inverse_shape` package remains available for reproducibility
and for lower-level research scripts.
"""

from gulati_quadrature.api import (
    PreparedBoundary,
    ProductionQConfig,
    ProductionQEngine,
    build_engine,
    cosine_trace,
    cycle_certificate,
    integrate_log_layer,
    inverse_square_chord_from_scale_phase,
    prepare_boundary,
    scale_phase_chord_squared,
    scale_phase_point,
    solve_pde,
    star_boundary,
)
from gulati_quadrature.surface_pde import (
    SurfacePDEConfig,
    SurfacePDENonconvergenceError,
    SurfacePDEResult,
    SurfacePDESolver,
    build_surface_pde_solver,
    solve_surface_pde,
)
from gulati_quadrature.three_d import (
    CadArchiveError,
    CertifiedPolyhedralSurfaceQJet,
    CompiledCadPanelSurface,
    CompiledCadSurface,
    CurvedPanelConfig,
    CurvedPanelSurface,
    ExactMesh,
    FeatureChannelConfig,
    FeatureRepaymentEvaluation,
    ManifoldRepairCertificate,
    ManifoldRepairConfig,
    MellinKondratievPanelRepayment3D,
    MeshPart,
    NearLinearContractError,
    PanelSingularRepaymentConfig,
    ProductionRieszQJet,
    ProductionSurfaceQEngine,
    RepairedTriangleMesh,
    SurfaceQConfig,
    SurfaceQEvaluation,
    archive_header,
    audit_round_trip,
    build_axisymmetric_conic_engine,
    build_axisymmetric_engine,
    build_compiled_cad_engine,
    build_conic_pencil_engine,
    build_curved_panel_engine,
    build_curved_panel_surface,
    build_mesh_engine,
    build_polyhedral_engine,
    build_radial_profile_engine,
    build_radial_quadric_panel_surface,
    build_repaired_cad_engine,
    build_repaired_mesh_engine,
    build_spheroid_engine,
    build_surface_engine,
    build_torus_engine,
    compile_cad_panels,
    compile_cad_surface,
    decode_mesh,
    encode_mesh,
    load_binary_stl_assembly,
    load_compiled_cad_panels,
    load_compiled_cad_surface,
    load_ifc_tessellation,
    repair_triangle_mesh,
    triangle_lumped_vertex_weights,
    write_archive,
)
from inverse_shape.transparent_tail import (
    GOLDEN_MULTIPLIER,
    CylindricalTransparentDtN,
    TransparentTailBranchError,
    TransparentTailEvaluation,
    TransparentTailMode,
    fibonacci,
    golden_tail_certificate,
    pde_spectral_shift,
    residue_class_sectors,
)

__all__ = [
    "CylindricalTransparentDtN",
    "PreparedBoundary",
    "ProductionQConfig",
    "ProductionQEngine",
    "CadArchiveError",
    "CertifiedPolyhedralSurfaceQJet",
    "CompiledCadPanelSurface",
    "CompiledCadSurface",
    "CurvedPanelConfig",
    "CurvedPanelSurface",
    "ExactMesh",
    "FeatureChannelConfig",
    "FeatureRepaymentEvaluation",
    "GOLDEN_MULTIPLIER",
    "ManifoldRepairCertificate",
    "ManifoldRepairConfig",
    "MellinKondratievPanelRepayment3D",
    "MeshPart",
    "NearLinearContractError",
    "PanelSingularRepaymentConfig",
    "ProductionRieszQJet",
    "ProductionSurfaceQEngine",
    "RepairedTriangleMesh",
    "SurfaceQConfig",
    "SurfaceQEvaluation",
    "SurfacePDEConfig",
    "SurfacePDENonconvergenceError",
    "SurfacePDEResult",
    "SurfacePDESolver",
    "TransparentTailBranchError",
    "TransparentTailEvaluation",
    "TransparentTailMode",
    "archive_header",
    "audit_round_trip",
    "build_axisymmetric_conic_engine",
    "build_axisymmetric_engine",
    "build_conic_pencil_engine",
    "build_compiled_cad_engine",
    "build_curved_panel_engine",
    "build_curved_panel_surface",
    "build_engine",
    "build_mesh_engine",
    "build_polyhedral_engine",
    "build_radial_profile_engine",
    "build_radial_quadric_panel_surface",
    "build_repaired_cad_engine",
    "build_repaired_mesh_engine",
    "build_spheroid_engine",
    "build_surface_engine",
    "build_surface_pde_solver",
    "build_torus_engine",
    "compile_cad_panels",
    "compile_cad_surface",
    "cosine_trace",
    "cycle_certificate",
    "decode_mesh",
    "encode_mesh",
    "fibonacci",
    "golden_tail_certificate",
    "inverse_square_chord_from_scale_phase",
    "integrate_log_layer",
    "load_binary_stl_assembly",
    "load_ifc_tessellation",
    "load_compiled_cad_panels",
    "load_compiled_cad_surface",
    "repair_triangle_mesh",
    "prepare_boundary",
    "pde_spectral_shift",
    "residue_class_sectors",
    "scale_phase_chord_squared",
    "scale_phase_point",
    "solve_pde",
    "solve_surface_pde",
    "star_boundary",
    "triangle_lumped_vertex_weights",
    "write_archive",
]
