"""Matrix-free boundary PDE calculus generated by the production 3D QJet.

Let ``A = Q_3 / (2*pi)``.  The operator is the discrete principal part of the
Laplace Dirichlet-to-Neumann map on a sampled surface.  This module applies
and solves equations generated by ``A`` without forming a matrix:

``laplace_dtn``
    ``g = A f``.
``poisson``
    ``A u = f`` on the weighted mean-zero subspace.
``screened_poisson``
    ``(A + mu I) u = f``.
``helmholtz``
    ``(A^2 - k^2 I + i eta I) u = f`` with ``eta > 0``.
``heat``
    ``partial_t u + A u = 0`` (the boundary Poisson semigroup).
``wave``
    ``partial_tt u + A^2 u = 0``.

These are boundary functional-calculus problems.  In particular, ``heat`` is
not advertised as a general volumetric heat solve, and ``poisson`` does not
include an arbitrary interior volume source.  A supplied volume particular
solution can be coupled to the boundary correction separately.

The implementation uses no NumPy or SciPy.  For fixed solver tolerances and
iteration counts, time is ``O(k N log N)`` and auxiliary storage is ``O(N)``.
The production QJet remains responsible for enforcing the no-quadratic
contract on every operator application.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Iterable

from inverse_shape.quadrature import BorrowComputeRepayLedger, _abs, _finite, _sqrt

from gulati_quadrature.three_d import ProductionSurfaceQEngine


ComplexVector = tuple[complex, ...]


class SurfacePDENonconvergenceError(RuntimeError):
    """Raised when a production boundary solve misses its requested residual."""


@dataclass(frozen=True)
class SurfacePDEConfig:
    """Fixed iteration and time-integration controls for surface PDE solves."""

    tolerance: float = 1.0e-10
    maximum_iterations: int = 240
    heat_steps: int = 2
    wave_steps: int = 32
    fail_on_nonconvergence: bool = True

    def __post_init__(self) -> None:
        if self.tolerance <= 0.0 or not _finite(self.tolerance):
            raise ValueError("PDE tolerance must be positive and finite")
        if self.maximum_iterations < 1:
            raise ValueError("maximum_iterations must be positive")
        if self.heat_steps < 1 or self.wave_steps < 1:
            raise ValueError("heat_steps and wave_steps must be positive")


@dataclass(frozen=True)
class SurfacePDEResult:
    """One matrix-free boundary PDE result and its audit information."""

    values: ComplexVector
    problem: str
    converged: bool
    iterations: int
    operator_applications: int
    relative_residual: float
    compression_inf_bound: float
    ledger: BorrowComputeRepayLedger
    stats: dict[str, object]


@dataclass(frozen=True)
class _CGResult:
    values: ComplexVector
    iterations: int
    relative_residual: float
    converged: bool


def _vector(values: Iterable[complex], n: int, name: str) -> ComplexVector:
    row = tuple(complex(value) for value in values)
    if len(row) != n:
        raise ValueError(f"{name} must contain one value per surface node")
    if any(not _finite(value.real) or not _finite(value.imag) for value in row):
        raise ValueError(f"{name} must contain finite values")
    return row


def _weighted_inner(
    weights: tuple[float, ...],
    left: ComplexVector,
    right: ComplexVector,
) -> complex:
    total = 0.0 + 0.0j
    compensation = 0.0 + 0.0j
    for weight, first, second in zip(weights, left, right, strict=True):
        contribution = weight * first.conjugate() * second
        corrected = contribution - compensation
        updated = total + corrected
        compensation = (updated - total) - corrected
        total = updated
    return total


def _weighted_norm(weights: tuple[float, ...], values: ComplexVector) -> float:
    energy = _weighted_inner(weights, values, values).real
    return _sqrt(max(energy, 0.0))


def _weighted_mean(weights: tuple[float, ...], values: ComplexVector) -> complex:
    total_weight = sum(weights)
    return sum(
        weight * value for weight, value in zip(weights, values, strict=True)
    ) / total_weight


def _project_mean_zero(weights: tuple[float, ...], values: ComplexVector) -> ComplexVector:
    mean = _weighted_mean(weights, values)
    return tuple(value - mean for value in values)


def _relative_residual(
    weights: tuple[float, ...],
    residual: ComplexVector,
    right_hand_side: ComplexVector,
) -> float:
    denominator = max(_weighted_norm(weights, right_hand_side), 1.0e-300)
    return _weighted_norm(weights, residual) / denominator


def _conjugate_gradient(
    apply: Callable[[ComplexVector], ComplexVector],
    right_hand_side: ComplexVector,
    weights: tuple[float, ...],
    *,
    tolerance: float,
    maximum_iterations: int,
    projector: Callable[[ComplexVector], ComplexVector] | None = None,
) -> _CGResult:
    """Weighted Hermitian positive-definite CG with ``O(N)`` storage."""

    rhs = projector(right_hand_side) if projector is not None else right_hand_side
    rhs_norm = _weighted_norm(weights, rhs)
    if rhs_norm <= 1.0e-300:
        return _CGResult((0.0j,) * len(rhs), 0, 0.0, True)
    values = (0.0j,) * len(rhs)
    residual = rhs
    direction = residual
    residual_energy = max(_weighted_inner(weights, residual, residual).real, 0.0)
    relative = _sqrt(residual_energy) / rhs_norm
    if relative <= tolerance:
        return _CGResult(values, 0, relative, True)

    for iteration in range(1, maximum_iterations + 1):
        applied = apply(direction)
        if projector is not None:
            applied = projector(applied)
        denominator_value = _weighted_inner(weights, direction, applied)
        denominator = denominator_value.real
        imaginary_allowance = 5.0e-11 * max(1.0, _abs(denominator_value))
        if _abs(denominator_value.imag) > imaginary_allowance or denominator <= 0.0:
            return _CGResult(values, iteration - 1, relative, False)
        step = residual_energy / denominator
        values = tuple(
            value + step * delta
            for value, delta in zip(values, direction, strict=True)
        )
        residual = tuple(
            value - step * delta
            for value, delta in zip(residual, applied, strict=True)
        )
        if projector is not None:
            values = projector(values)
            residual = projector(residual)
        next_energy = max(_weighted_inner(weights, residual, residual).real, 0.0)
        relative = _sqrt(next_energy) / rhs_norm
        if relative <= tolerance:
            return _CGResult(values, iteration, relative, True)
        beta = next_energy / max(residual_energy, 1.0e-300)
        direction = tuple(
            value + beta * previous
            for value, previous in zip(residual, direction, strict=True)
        )
        residual_energy = next_energy
    return _CGResult(values, maximum_iterations, relative, False)


def _bicgstab(
    apply: Callable[[ComplexVector], ComplexVector],
    right_hand_side: ComplexVector,
    weights: tuple[float, ...],
    *,
    tolerance: float,
    maximum_iterations: int,
) -> _CGResult:
    """Weighted BiCGSTAB for the damped non-Hermitian Helmholtz system."""

    rhs_norm = _weighted_norm(weights, right_hand_side)
    if rhs_norm <= 1.0e-300:
        return _CGResult((0.0j,) * len(right_hand_side), 0, 0.0, True)
    values = (0.0j,) * len(right_hand_side)
    residual = right_hand_side
    shadow = residual
    direction = (0.0j,) * len(residual)
    image = (0.0j,) * len(residual)
    rho_previous = 1.0 + 0.0j
    alpha = 1.0 + 0.0j
    omega = 1.0 + 0.0j
    relative = _weighted_norm(weights, residual) / rhs_norm
    breakdown = 1.0e-30

    for iteration in range(1, maximum_iterations + 1):
        rho = _weighted_inner(weights, shadow, residual)
        if _abs(rho) <= breakdown or _abs(omega) <= breakdown:
            return _CGResult(values, iteration - 1, relative, False)
        beta = (rho / rho_previous) * (alpha / omega)
        direction = tuple(
            r + beta * (p - omega * v)
            for r, p, v in zip(residual, direction, image, strict=True)
        )
        image = apply(direction)
        shadow_image = _weighted_inner(weights, shadow, image)
        if _abs(shadow_image) <= breakdown:
            return _CGResult(values, iteration - 1, relative, False)
        alpha = rho / shadow_image
        intermediate = tuple(
            r - alpha * v for r, v in zip(residual, image, strict=True)
        )
        intermediate_relative = _weighted_norm(weights, intermediate) / rhs_norm
        if intermediate_relative <= tolerance:
            values = tuple(
                value + alpha * delta
                for value, delta in zip(values, direction, strict=True)
            )
            return _CGResult(values, iteration, intermediate_relative, True)
        transformed = apply(intermediate)
        transformed_energy = _weighted_inner(weights, transformed, transformed).real
        if transformed_energy <= breakdown:
            return _CGResult(values, iteration - 1, relative, False)
        omega = (
            _weighted_inner(weights, transformed, intermediate)
            / transformed_energy
        )
        values = tuple(
            value + alpha * first + omega * second
            for value, first, second in zip(
                values, direction, intermediate, strict=True
            )
        )
        residual = tuple(
            first - omega * second
            for first, second in zip(intermediate, transformed, strict=True)
        )
        relative = _weighted_norm(weights, residual) / rhs_norm
        if relative <= tolerance:
            return _CGResult(values, iteration, relative, True)
        rho_previous = rho
    return _CGResult(values, maximum_iterations, relative, False)


class SurfacePDESolver:
    """Boundary PDE functional calculus over a production surface QJet."""

    def __init__(
        self,
        engine: ProductionSurfaceQEngine,
        *,
        config: SurfacePDEConfig | None = None,
    ) -> None:
        self.engine = engine
        self.config = config or SurfacePDEConfig()
        self.n = int(engine.n)
        self.weights = tuple(float(value) for value in engine.weights)
        if len(self.weights) != self.n or any(value <= 0.0 for value in self.weights):
            raise ValueError("surface PDE weights must be positive")
        engine_config = getattr(engine, "config", None)
        if engine_config is not None and float(engine_config.kernel_power) != 3.0:
            raise ValueError("surface PDE solves require the Q_3 kernel")
        self._operator_applications = 0
        self._maximum_compression_bound = 0.0

    def _begin(self) -> None:
        self._operator_applications = 0
        self._maximum_compression_bound = 0.0

    def _apply_dtn(self, values: ComplexVector) -> ComplexVector:
        evaluation = self.engine.apply_dtn_principal(values)
        self._operator_applications += 1
        self._maximum_compression_bound = max(
            self._maximum_compression_bound,
            float(getattr(evaluation, "compression_inf_bound", 0.0)),
        )
        return tuple(complex(value) for value in evaluation.values)

    def _result(
        self,
        problem: str,
        values: ComplexVector,
        *,
        converged: bool,
        iterations: int,
        relative_residual: float,
        equation: str,
        time_method: str | None = None,
        time_steps: int | None = None,
    ) -> SurfacePDEResult:
        if not converged and self.config.fail_on_nonconvergence:
            raise SurfacePDENonconvergenceError(
                f"{problem} missed tolerance {self.config.tolerance:.3e}; "
                f"relative residual={relative_residual:.3e}"
            )
        stats: dict[str, object] = {
            "public_api": "gulati_quadrature.SurfacePDESolver",
            "problem": problem,
            "equation": equation,
            "nodes": self.n,
            "iterations": int(iterations),
            "operator_applications": self._operator_applications,
            "relative_residual": float(relative_residual),
            "compression_inf_bound": self._maximum_compression_bound,
            "converged": bool(converged),
            "operator": "A = Q_3 / (2*pi)",
            "operator_role": "discrete principal Laplace DtN operator",
            "pde_scope": "boundary functional calculus; no arbitrary volume source",
            "dense_operator_stored": False,
            "quadratic_fallback": False,
            "auxiliary_storage_big_o": "O(N)",
            "solve_time_big_o": "O(k N log N) for k QJet applications",
        }
        if time_method is not None:
            stats["time_method"] = time_method
            stats["time_steps"] = int(time_steps or 0)
        ledger = BorrowComputeRepayLedger(
            borrowed=(
                "surface geometry and lumped surface measure",
                "fixed-order production QJet for Q_3",
            ),
            computed=(
                equation,
                "weighted matrix-free Krylov or rational time propagation",
            ),
            repaid=(
                "Q_3 physical normalization by 1/(2*pi)",
                "constant channel and mean-zero gauge where required",
                "all Krylov work through QJet applications",
                "no dense surface operator or distance matrix",
            ),
            residuals=(
                ("relative_equation_residual", float(relative_residual)),
                ("maximum_qjet_compression_inf_bound", self._maximum_compression_bound),
            ),
            residual_norm=max(relative_residual, self._maximum_compression_bound),
            status="borrowed_repaid" if converged else "not_converged",
            notes=(
                "This result solves a boundary equation generated by the discrete "
                "DtN principal operator. Continuum discretization error must be "
                "audited separately from the reported algebraic residual."
            ),
        )
        return SurfacePDEResult(
            values=values,
            problem=problem,
            converged=converged,
            iterations=int(iterations),
            operator_applications=self._operator_applications,
            relative_residual=float(relative_residual),
            compression_inf_bound=self._maximum_compression_bound,
            ledger=ledger,
            stats=stats,
        )

    def apply_laplace_dtn(self, values: Iterable[complex]) -> SurfacePDEResult:
        """Apply ``A = Q_3/(2*pi)`` to Dirichlet boundary data."""

        self._begin()
        vector = _vector(values, self.n, "values")
        output = self._apply_dtn(vector)
        return self._result(
            "laplace_dtn",
            output,
            converged=True,
            iterations=0,
            relative_residual=0.0,
            equation="g = A f",
        )

    def solve_poisson(
        self,
        right_hand_side: Iterable[complex],
        *,
        mass: float = 0.0,
        tolerance: float | None = None,
        maximum_iterations: int | None = None,
    ) -> SurfacePDEResult:
        """Solve ``(A + mass I)u=f``; use the mean-zero gauge when ``mass=0``."""

        mass_value = float(mass)
        if mass_value < 0.0 or not _finite(mass_value):
            raise ValueError("Poisson mass must be nonnegative and finite")
        self._begin()
        rhs = _vector(right_hand_side, self.n, "right_hand_side")
        projector = None
        if mass_value == 0.0:
            projector = lambda row: _project_mean_zero(self.weights, row)
            rhs = projector(rhs)

        def apply_system(candidate: ComplexVector) -> ComplexVector:
            applied = self._apply_dtn(candidate)
            return tuple(
                value + mass_value * original
                for value, original in zip(applied, candidate, strict=True)
            )

        solved = _conjugate_gradient(
            apply_system,
            rhs,
            self.weights,
            tolerance=float(tolerance or self.config.tolerance),
            maximum_iterations=int(maximum_iterations or self.config.maximum_iterations),
            projector=projector,
        )
        problem = "poisson" if mass_value == 0.0 else "screened_poisson"
        return self._result(
            problem,
            solved.values,
            converged=solved.converged,
            iterations=solved.iterations,
            relative_residual=solved.relative_residual,
            equation=f"(A + {mass_value:.17g} I) u = f",
        )

    def solve_helmholtz(
        self,
        right_hand_side: Iterable[complex],
        *,
        wavenumber: float,
        damping: float = 0.2,
        tolerance: float | None = None,
        maximum_iterations: int | None = None,
    ) -> SurfacePDEResult:
        """Solve the damped boundary resolvent ``(A^2-k^2+i eta)u=f``."""

        wave_number = float(wavenumber)
        eta = float(damping)
        if wave_number < 0.0 or not _finite(wave_number):
            raise ValueError("wavenumber must be nonnegative and finite")
        if eta <= 0.0 or not _finite(eta):
            raise ValueError("Helmholtz damping must be positive and finite")
        self._begin()
        rhs = _vector(right_hand_side, self.n, "right_hand_side")
        squared_wave_number = wave_number * wave_number

        def apply_real_part(candidate: ComplexVector) -> ComplexVector:
            first = self._apply_dtn(candidate)
            second = self._apply_dtn(first)
            return tuple(
                value - squared_wave_number * original
                for value, original in zip(second, candidate, strict=True)
            )

        def apply_system(candidate: ComplexVector) -> ComplexVector:
            real_part = apply_real_part(candidate)
            return tuple(
                value + 1j * eta * original
                for value, original in zip(real_part, candidate, strict=True)
            )

        solved = _bicgstab(
            apply_system,
            rhs,
            self.weights,
            tolerance=float(tolerance or self.config.tolerance),
            maximum_iterations=int(maximum_iterations or self.config.maximum_iterations),
        )
        output = apply_system(solved.values)
        residual = tuple(
            value - target for value, target in zip(output, rhs, strict=True)
        )
        actual_relative = _relative_residual(self.weights, residual, rhs)
        requested = float(tolerance or self.config.tolerance)
        converged = solved.converged and actual_relative <= 5.0 * requested
        return self._result(
            "helmholtz",
            solved.values,
            converged=converged,
            iterations=solved.iterations,
            relative_residual=actual_relative,
            equation=f"(A^2 - {squared_wave_number:.17g} I + i {eta:.17g} I) u = f",
        )

    def _third_order_powers(
        self,
        values: ComplexVector,
    ) -> tuple[ComplexVector, ComplexVector, ComplexVector]:
        first = self._apply_dtn(values)
        second = self._apply_dtn(first)
        third = self._apply_dtn(second)
        return first, second, third

    def solve_heat(
        self,
        initial_values: Iterable[complex],
        *,
        time: float,
        steps: int | None = None,
        tolerance: float | None = None,
        maximum_iterations: int | None = None,
    ) -> SurfacePDEResult:
        """Propagate ``u_t + A u=0`` with a diagonal ``[3/3]`` Pade step."""

        final_time = float(time)
        if final_time < 0.0 or not _finite(final_time):
            raise ValueError("heat time must be nonnegative and finite")
        step_count = int(steps or self.config.heat_steps)
        if step_count < 1:
            raise ValueError("heat steps must be positive")
        self._begin()
        values = _vector(initial_values, self.n, "initial_values")
        if final_time == 0.0:
            return self._result(
                "heat",
                values,
                converged=True,
                iterations=0,
                relative_residual=0.0,
                equation="partial_t u + A u = 0",
                time_method="diagonal Pade [3/3]",
                time_steps=step_count,
            )
        step_size = final_time / step_count
        half = 0.5 * step_size
        tenth = 0.1 * step_size * step_size
        one_twentieth = step_size * step_size * step_size / 120.0
        total_iterations = 0
        maximum_residual = 0.0
        converged = True
        requested = float(tolerance or self.config.tolerance)
        limit = int(maximum_iterations or self.config.maximum_iterations)

        for _step in range(step_count):
            first, second, third = self._third_order_powers(values)
            rhs = tuple(
                original - half * a1 + tenth * a2 - one_twentieth * a3
                for original, a1, a2, a3 in zip(
                    values, first, second, third, strict=True
                )
            )

            def denominator(candidate: ComplexVector) -> ComplexVector:
                a1, a2, a3 = self._third_order_powers(candidate)
                return tuple(
                    original + half * first_value + tenth * second_value
                    + one_twentieth * third_value
                    for original, first_value, second_value, third_value in zip(
                        candidate, a1, a2, a3, strict=True
                    )
                )

            solved = _conjugate_gradient(
                denominator,
                rhs,
                self.weights,
                tolerance=requested,
                maximum_iterations=limit,
            )
            values = solved.values
            total_iterations += solved.iterations
            maximum_residual = max(maximum_residual, solved.relative_residual)
            converged &= solved.converged
        return self._result(
            "heat",
            values,
            converged=converged,
            iterations=total_iterations,
            relative_residual=maximum_residual,
            equation="partial_t u + A u = 0",
            time_method="diagonal Pade [3/3]",
            time_steps=step_count,
        )

    def solve_wave(
        self,
        initial_displacement: Iterable[complex],
        *,
        time: float,
        initial_velocity: Iterable[complex] | None = None,
        steps: int | None = None,
        tolerance: float | None = None,
        maximum_iterations: int | None = None,
    ) -> SurfacePDEResult:
        """Propagate ``u_tt + A^2 u=0`` with implicit midpoint/Newmark."""

        final_time = float(time)
        if final_time < 0.0 or not _finite(final_time):
            raise ValueError("wave time must be nonnegative and finite")
        step_count = int(steps or self.config.wave_steps)
        if step_count < 1:
            raise ValueError("wave steps must be positive")
        self._begin()
        displacement = _vector(
            initial_displacement,
            self.n,
            "initial_displacement",
        )
        velocity = (
            (0.0j,) * self.n
            if initial_velocity is None
            else _vector(initial_velocity, self.n, "initial_velocity")
        )
        if final_time == 0.0:
            return self._result(
                "wave",
                displacement,
                converged=True,
                iterations=0,
                relative_residual=0.0,
                equation="partial_tt u + A^2 u = 0",
                time_method="implicit midpoint/Newmark",
                time_steps=step_count,
            )
        step_size = final_time / step_count
        coefficient = 0.25 * step_size * step_size
        total_iterations = 0
        maximum_residual = 0.0
        converged = True
        requested = float(tolerance or self.config.tolerance)
        limit = int(maximum_iterations or self.config.maximum_iterations)

        def apply_square(candidate: ComplexVector) -> ComplexVector:
            return self._apply_dtn(self._apply_dtn(candidate))

        for _step in range(step_count):
            square = apply_square(displacement)
            rhs = tuple(
                value - coefficient * curvature + step_size * speed
                for value, curvature, speed in zip(
                    displacement, square, velocity, strict=True
                )
            )

            def denominator(candidate: ComplexVector) -> ComplexVector:
                square_candidate = apply_square(candidate)
                return tuple(
                    value + coefficient * curvature
                    for value, curvature in zip(
                        candidate, square_candidate, strict=True
                    )
                )

            solved = _conjugate_gradient(
                denominator,
                rhs,
                self.weights,
                tolerance=requested,
                maximum_iterations=limit,
            )
            next_displacement = solved.values
            square_sum = apply_square(
                tuple(
                    left + right
                    for left, right in zip(
                        displacement, next_displacement, strict=True
                    )
                )
            )
            velocity = tuple(
                value - 0.5 * step_size * acceleration
                for value, acceleration in zip(velocity, square_sum, strict=True)
            )
            displacement = next_displacement
            total_iterations += solved.iterations
            maximum_residual = max(maximum_residual, solved.relative_residual)
            converged &= solved.converged
        return self._result(
            "wave",
            displacement,
            converged=converged,
            iterations=total_iterations,
            relative_residual=maximum_residual,
            equation="partial_tt u + A^2 u = 0",
            time_method="implicit midpoint/Newmark",
            time_steps=step_count,
        )

    def solve(
        self,
        problem: str,
        values: Iterable[complex],
        **parameters: object,
    ) -> SurfacePDEResult:
        """Dispatch one supported boundary PDE by its public problem name."""

        name = str(problem).strip().lower()
        if name in {"laplace", "laplace_dtn", "dtn"}:
            return self.apply_laplace_dtn(values)
        if name == "poisson":
            return self.solve_poisson(values, **parameters)
        if name in {"screened_poisson", "yukawa"}:
            if "mass" not in parameters:
                raise ValueError("screened_poisson requires a positive mass")
            if float(parameters["mass"]) <= 0.0:
                raise ValueError("screened_poisson requires a positive mass")
            return self.solve_poisson(values, **parameters)
        if name in {"helmholtz", "helmholtz_resolvent"}:
            return self.solve_helmholtz(values, **parameters)
        if name in {"heat", "poisson_semigroup"}:
            return self.solve_heat(values, **parameters)
        if name == "wave":
            return self.solve_wave(values, **parameters)
        raise ValueError(f"unknown surface PDE problem: {problem}")


def build_surface_pde_solver(
    engine: ProductionSurfaceQEngine,
    *,
    config: SurfacePDEConfig | None = None,
) -> SurfacePDESolver:
    """Build a matrix-free boundary PDE solver over an existing surface QJet."""

    return SurfacePDESolver(engine, config=config)


def solve_surface_pde(
    engine: ProductionSurfaceQEngine,
    values: Iterable[complex],
    problem: str,
    *,
    config: SurfacePDEConfig | None = None,
    **parameters: object,
) -> SurfacePDEResult:
    """One-shot public wrapper for a 3D boundary PDE solve."""

    return build_surface_pde_solver(engine, config=config).solve(
        problem,
        values,
        **parameters,
    )


__all__ = [
    "SurfacePDEConfig",
    "SurfacePDENonconvergenceError",
    "SurfacePDEResult",
    "SurfacePDESolver",
    "build_surface_pde_solver",
    "solve_surface_pde",
]
